package com.robsartin.jsgb.demo;

import com.robsartin.jsgb.graph.Arc;
import com.robsartin.jsgb.graph.Gb;
import com.robsartin.jsgb.graph.Graph;
import com.robsartin.jsgb.graph.Util;
import com.robsartin.jsgb.graph.Vertex;
import com.robsartin.jsgb.io.GbIo;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

/**
 * Port of {@code test_sample}: prints salient characteristics of generated graphs so the output can
 * be compared with {@code sample.correct}. {@link #main} grows one stanza at a time as generators
 * are ported; {@link #printSample} is the printer every oracle test uses.
 */
public final class TestSample {

  private TestSample() {}

  /** Runs the sample sequence ported so far, in {@code test_sample.w} order. */
  public static void main(String[] args) {
    PrintStream out = new PrintStream(System.out, true, StandardCharsets.ISO_8859_1);
    out.print("GraphBase samples generated by test_sample:\n");
    // Stanzas are appended here by later tasks.
  }

  /**
   * {@code print_sample(g, n)}: global characteristics of {@code g} and vertex {@code n}; recycles
   * {@code g}.
   */
  public static void printSample(Graph g, int n, PrintStream out) {
    out.print("\n");
    if (g == null) {
      out.print("Ooops, we just ran into panic code " + Gb.panicCode + "!\n");
      if (GbIo.ioErrors != 0) {
        out.print("(The I/O error code is 0x" + Long.toHexString(GbIo.ioErrors) + ")\n");
      }
      return;
    }
    String s = g.utilTypes;
    out.print("\"" + g.id + "\"\n" + g.n + " vertices, " + g.m + " arcs, util_types " + s);
    prUtil(g.uu, s.charAt(8), 0, s, out);
    prUtil(g.vv, s.charAt(9), 0, s, out);
    prUtil(g.ww, s.charAt(10), 0, s, out);
    prUtil(g.xx, s.charAt(11), 0, s, out);
    prUtil(g.yy, s.charAt(12), 0, s, out);
    prUtil(g.zz, s.charAt(13), 0, s, out);
    out.print("\n");
    out.print("V" + n + ": ");
    if (n >= g.n || n < 0) {
      out.print("index is out of range!\n");
    } else {
      prVert(g.vertices[n], 1, s, out);
      out.print("\n");
    }
    Gb.recycle(g);
  }

  private static void prVert(Vertex v, int l, String s, PrintStream out) {
    if (v == null) {
      out.print("NULL");
      return;
    }
    out.print("\"" + v.name + "\"");
    prUtil(v.u, s.charAt(0), l - 1, s, out);
    prUtil(v.v, s.charAt(1), l - 1, s, out);
    prUtil(v.w, s.charAt(2), l - 1, s, out);
    prUtil(v.x, s.charAt(3), l - 1, s, out);
    prUtil(v.y, s.charAt(4), l - 1, s, out);
    prUtil(v.z, s.charAt(5), l - 1, s, out);
    if (l > 0) {
      for (Arc a = v.arcs; a != null; a = a.next) {
        out.print("\n   ");
        prArc(a, 1, s, out);
      }
    }
  }

  private static void prArc(Arc a, int l, String s, PrintStream out) {
    out.print("->");
    prVert(a.tip, 0, s, out);
    if (l > 0) {
      out.print(", " + a.len);
      prUtil(a.a, s.charAt(6), l - 1, s, out);
      prUtil(a.b, s.charAt(7), l - 1, s, out);
    }
  }

  private static void prUtil(Util u, char c, int l, String s, PrintStream out) {
    switch (c) {
      case 'I' -> out.print("[" + u.I + "]");
      case 'S' -> out.print("[\"" + (u.ref == null ? "(null)" : u.S()) + "\"]");
      case 'A' -> {
        if (l < 0) {
          return;
        }
        out.print("[");
        if (u.ref == null) {
          out.print("NULL");
        } else {
          prArc(u.A(), l, s, out);
        }
        out.print("]");
      }
      case 'V' -> {
        if (l < 0) {
          return;
        }
        out.print("[");
        if (u.ref == null && u.I == 1) {
          out.print("ONE"); // gb_gates' boolean vertex; a V slot holding the value 1
        } else {
          prVert(u.V(), l, s, out);
        }
        out.print("]");
      }
      default -> {}
    }
  }
}
