package com.robsartin.jsgb.demo;

import com.robsartin.jsgb.basic.Basic;
import com.robsartin.jsgb.books.Books;
import com.robsartin.jsgb.econ.Econ;
import com.robsartin.jsgb.games.Games;
import com.robsartin.jsgb.gates.Gates;
import com.robsartin.jsgb.graph.Arc;
import com.robsartin.jsgb.graph.Gb;
import com.robsartin.jsgb.graph.Graph;
import com.robsartin.jsgb.graph.Util;
import com.robsartin.jsgb.graph.Vertex;
import com.robsartin.jsgb.io.GbIo;
import com.robsartin.jsgb.lisa.Lisa;
import com.robsartin.jsgb.miles.Miles;
import com.robsartin.jsgb.plane.Plane;
import com.robsartin.jsgb.raman.Raman;
import com.robsartin.jsgb.rand.Rand;
import com.robsartin.jsgb.roget.Roget;
import com.robsartin.jsgb.save.Save;
import com.robsartin.jsgb.words.Words;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;

/**
 * Port of {@code test_sample}: prints salient characteristics of generated graphs so the output can
 * be compared with {@code sample.correct}. {@link #run} reproduces all sixteen stanzas; {@link
 * #printSample} is the printer every oracle test uses.
 */
public final class TestSample {

  private TestSample() {}

  /** Runs the full sample sequence, writing {@code test.gb} in the current directory. */
  public static void main(String[] args) {
    run(new PrintStream(System.out, true, StandardCharsets.ISO_8859_1), Path.of(""));
  }

  /**
   * Runs the full sample sequence, in {@code test_sample.w} order, printing to {@code out} and
   * writing {@code test.gb} under {@code workDir}.
   */
  public static void run(PrintStream out, Path workDir) {
    out.print("GraphBase samples generated by test_sample:\n");
    long[] dst = {0x20000000L, 0x10000000L, 0x10000000L};
    // Save a graph to be restored later (test_sample.w section 6).
    Graph g = Rand.randomGraph(3L, 10L, 1L, 1L, 0L, null, dst, 1L, 2L, 1L);
    Graph gg = Basic.complement(g, 1L, 1L, 0L);
    Vertex v = Gb.allocVertices(gg, 1)[0];
    v.name = Gb.saveString("Testing");
    gg.utilTypes = gg.utilTypes.substring(0, 10) + 'V' + gg.utilTypes.substring(11);
    gg.ww.V(v);
    Save.saveGraph(gg, workDir.resolve("test.gb").toString());
    Gb.recycle(g);
    Gb.recycle(gg);
    printSample(Raman.raman(31L, 3L, 0L, 4L), 4, out);
    printSample(Basic.board(1L, 1L, 2L, -33L, 1L, -0x40000000L - 0x40000000L, 1L), 2000, out);
    printSample(Basic.subsets(32L, 18L, 16L, 0L, 999L, -999L, 0x80000000L, 1L), 1, out);
    g = Save.restoreGraph(workDir.resolve("test.gb").toString());
    long i = Rand.randomLengths(g, 0L, 10L, 12L, dst, 2L);
    if (i != 0) {
      out.print("\nFailure code " + i + " returned by random_lengths!\n");
    } else {
      gg = Rand.randomGraph(3L, 10L, 1L, 1L, 0L, null, dst, 1L, 2L, 1L);
      printSample(Basic.gunion(g, gg, 1L, 0L), 2, out);
      Gb.recycle(g);
      Gb.recycle(gg);
    }
    printSample(Gates.partialGates(Gates.risc(0L), 1L, 43210L, 98765L, null), 79, out);
    printSample(Books.book("homer", 500L, 400L, 2L, 12L, 10000L, -123456L, 789L), 81, out);
    printSample(Econ.econ(40L, 0L, 400L, -111L), 11, out);
    printSample(Games.games(60L, 70L, 80L, -90L, -101L, 60L, 0L, 999999999L), 14, out);
    printSample(Miles.miles(50L, -500L, 100L, 1L, 500L, 5L, 314159L), 20, out);
    printSample(
        Lisa.planeLisa(100L, 100L, 50L, 1L, 300L, 1L, 200L, 50L * 299L * 199L, 200L * 299L * 199L),
        1294,
        out);
    printSample(Plane.planeMiles(50L, 500L, -100L, 1L, 1L, 40000L, 271818L), 14, out);
    printSample(Rand.randomBigraph(300L, 3L, 1000L, -1L, null, dst, -500L, 500L, 666L), 3, out);
    printSample(Roget.roget(1000L, 3L, 1009L, 1009L), 40, out);
    long[] wt = {100, -80589, 50000, 18935, -18935, 18935, 18935, 18935, 18935};
    printSample(Words.words(100L, wt, 70000000L, 69L), 5, out);
    wt[1]++;
    printSample(Words.words(100L, wt, 70000000L, 69L), 5, out);
    printSample(Words.words(0L, null, 0L, 69L), 5555, out);
  }

  /**
   * {@code print_sample(g, n)}: global characteristics of {@code g} and vertex {@code n}; recycles
   * {@code g}.
   */
  public static void printSample(Graph g, int n, PrintStream out) {
    out.print("\n");
    if (g == null) {
      out.print("Ooops, we just ran into panic code " + Gb.panicCode + "!\n");
      if (GbIo.ioErrors != 0) {
        out.print("(The I/O error code is 0x" + Long.toHexString(GbIo.ioErrors) + ")\n");
      }
      return;
    }
    String s = g.utilTypes;
    out.print("\"" + g.id + "\"\n" + g.n + " vertices, " + g.m + " arcs, util_types " + s);
    prUtil(g.uu, s.charAt(8), 0, s, out);
    prUtil(g.vv, s.charAt(9), 0, s, out);
    prUtil(g.ww, s.charAt(10), 0, s, out);
    prUtil(g.xx, s.charAt(11), 0, s, out);
    prUtil(g.yy, s.charAt(12), 0, s, out);
    prUtil(g.zz, s.charAt(13), 0, s, out);
    out.print("\n");
    out.print("V" + n + ": ");
    if (n >= g.n || n < 0) {
      out.print("index is out of range!\n");
    } else {
      prVert(g.vertices[n], 1, s, out);
      out.print("\n");
    }
    Gb.recycle(g);
  }

  private static void prVert(Vertex v, int l, String s, PrintStream out) {
    if (v == null) {
      out.print("NULL");
      return;
    }
    if (v == Gb.ONE) {
      out.print("ONE"); // gb_gates' boolean vertex
      return;
    }
    out.print("\"" + v.name + "\"");
    prUtil(v.u, s.charAt(0), l - 1, s, out);
    prUtil(v.v, s.charAt(1), l - 1, s, out);
    prUtil(v.w, s.charAt(2), l - 1, s, out);
    prUtil(v.x, s.charAt(3), l - 1, s, out);
    prUtil(v.y, s.charAt(4), l - 1, s, out);
    prUtil(v.z, s.charAt(5), l - 1, s, out);
    if (l > 0) {
      for (Arc a = v.arcs; a != null; a = a.next) {
        out.print("\n   ");
        prArc(a, 1, s, out);
      }
    }
  }

  private static void prArc(Arc a, int l, String s, PrintStream out) {
    out.print("->");
    prVert(a.tip, 0, s, out);
    if (l > 0) {
      out.print(", " + a.len);
      prUtil(a.a, s.charAt(6), l - 1, s, out);
      prUtil(a.b, s.charAt(7), l - 1, s, out);
    }
  }

  private static void prUtil(Util u, char c, int l, String s, PrintStream out) {
    switch (c) {
      case 'I' -> out.print("[" + u.I + "]");
      case 'S' -> out.print("[\"" + (u.ref == null ? "(null)" : u.S()) + "\"]");
      case 'A' -> {
        if (l < 0) {
          return;
        }
        out.print("[");
        if (u.ref == null) {
          out.print("NULL");
        } else {
          prArc(u.A(), l, s, out);
        }
        out.print("]");
      }
      case 'V' -> {
        if (l < 0) {
          return;
        }
        out.print("[");
        prVert(u.V(), l, s, out);
        out.print("]");
      }
      default -> {}
    }
  }
}
