package com.robsartin.jsgb.demo;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Reads {@code sample.correct}, the SGB distribution's own record of what {@code test_sample}
 * prints: a header line followed by one stanza per generator call, each stanza the output of one
 * {@code print_sample}. Every stanza begins with the leading {@code "\n"} that {@code print_sample}
 * prints first, so a new stanza starts at each blank line.
 */
final class SampleCorrect {

  static final String HEADER = "GraphBase samples generated by test_sample:\n";

  private static final List<String> STANZAS = new ArrayList<>();

  static {
    String content = readResource("/oracle/sample.correct");
    if (!content.startsWith(HEADER)) {
      throw new IllegalStateException("sample.correct does not start with the expected header");
    }
    String rest = content.substring(HEADER.length());
    String[] lines = rest.split("\n");
    StringBuilder current = null;
    for (String line : lines) {
      if (line.isEmpty()) {
        if (current != null) {
          STANZAS.add(current.toString());
        }
        current = new StringBuilder("\n");
      } else if (current != null) {
        current.append(line).append("\n");
      }
    }
    if (current != null) {
      STANZAS.add(current.toString());
    }
  }

  private SampleCorrect() {}

  /** The i-th stanza (0-based) of {@code sample.correct}, including its leading newline. */
  static String stanza(int i) {
    return STANZAS.get(i);
  }

  private static String readResource(String path) {
    try (InputStream in = SampleCorrect.class.getResourceAsStream(path)) {
      if (in == null) {
        throw new IllegalStateException("missing classpath resource " + path);
      }
      return new String(in.readAllBytes(), StandardCharsets.ISO_8859_1);
    } catch (IOException e) {
      throw new UncheckedIOException(e);
    }
  }
}
