package com.robsartin.jsgb.demo;

import static org.assertj.core.api.Assertions.assertThat;

import com.robsartin.jsgb.basic.Basic;
import com.robsartin.jsgb.graph.Gb;
import com.robsartin.jsgb.graph.Graph;
import com.robsartin.jsgb.graph.Vertex;
import com.robsartin.jsgb.raman.Raman;
import com.robsartin.jsgb.rand.Rand;
import com.robsartin.jsgb.save.Save;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class TestSampleTest {

  @TempDir Path dir;

  private static final long[] DST = {0x20000000L, 0x10000000L, 0x10000000L};

  @Test
  @DisplayName("print_sample reports a panic exactly as the C does")
  void shouldPrintPanicWhenGraphIsNull() {
    com.robsartin.jsgb.graph.Gb.panicCode = 30;
    com.robsartin.jsgb.io.GbIo.ioErrors = 0;
    String out = Oracle.capture(ps -> TestSample.printSample(null, 0, ps));
    assertThat(out).isEqualTo("\nOoops, we just ran into panic code 30!\n");
  }

  @Test
  @DisplayName("print_sample prints a small hand-built graph with util types")
  void shouldPrintGraphWhenVertexHasArcsAndSlots() {
    com.robsartin.jsgb.graph.Graph g = com.robsartin.jsgb.graph.Gb.newGraph(2L);
    g.id = "hand";
    g.utilTypes = "IZZZZZZAZZZZZZ";
    g.vertices[0].name = "a";
    g.vertices[1].name = "b";
    g.vertices[0].u.I = 7;
    com.robsartin.jsgb.graph.Gb.newEdge(g.vertices[0], g.vertices[1], 3L);
    g.vertices[0].arcs.b.A(g.vertices[1].arcs);
    String out = Oracle.capture(ps -> TestSample.printSample(g, 0, ps));
    assertThat(out)
        .isEqualTo(
            "\n\"hand\"\n2 vertices, 2 arcs, util_types IZZZZZZAZZZZZZ\nV0: \"a\"[7]\n   ->\"b\"[0], 3[->\"a\"[7]]\n");
  }

  @Test
  @DisplayName(
      "print_sample prints V, S and A slots at every depth exactly as the C, including (null) and NULL")
  void shouldPrintSlotVariantsWhenGraphUsesSeveralUtilTypes() {
    Graph g = Gb.newGraph(2L);
    g.id = "slots";
    g.utilTypes = "VSAZZZZZVIZZZZ"; // u=V v=S w=A; uu=V vv=I
    g.vertices[0].name = "a";
    g.vertices[1].name = "b";
    g.vertices[0].u.V(g.vertices[1]);
    g.vertices[1].v.S("s");
    Gb.newArc(g.vertices[0], g.vertices[1], 5L);
    g.vertices[1].w.A(g.vertices[0].arcs);
    g.uu.V(g.vertices[0]);
    g.vv.I = 9;
    String out = Oracle.capture(ps -> TestSample.printSample(g, 0, ps));
    assertThat(out)
        .isEqualTo(
            "\n\"slots\"\n2 vertices, 1 arcs, util_types VSAZZZZZVIZZZZ[\"a\"[\"(null)\"]][9]\nV0: \"a\"[\"b\"[\"s\"]][\"(null)\"][NULL]\n   ->\"b\"[\"s\"], 5\n");
  }

  @Test
  @DisplayName(
      "print_sample prints the boolean ONE, an arc-valued slot, a null tip and an out-of-range index")
  void shouldPrintOneAndNullTipWhenPresent() {
    Graph g = Gb.newGraph(2L);
    g.id = "one";
    g.utilTypes = "VSAZZZZZZZZZZZ";
    g.vertices[0].name = "a";
    g.vertices[1].name = "b";
    g.vertices[1].u.V(Gb.ONE); // gb_gates' boolean ONE
    g.vertices[1].v.S("s");
    Gb.newArc(g.vertices[0], g.vertices[1], 5L);
    g.vertices[1].w.A(g.vertices[0].arcs);
    Gb.newArc(g.vertices[1], null, 7L); // an arc with no tip prints NULL
    String out = Oracle.capture(ps -> TestSample.printSample(g, 1, ps));
    assertThat(out)
        .isEqualTo(
            "\n\"one\"\n2 vertices, 2 arcs, util_types VSAZZZZZZZZZZZ\nV1: \"b\"[ONE][\"s\"][->\"b\"[\"s\"]]\n   ->NULL, 7\n");
    Graph h = Gb.newGraph(1L);
    h.id = "h";
    assertThat(Oracle.capture(ps -> TestSample.printSample(h, 5, ps)))
        .isEqualTo(
            "\n\"h\"\n1 vertices, 0 arcs, util_types ZZZZZZZZZZZZZZ\nV5: index is out of range!\n");
  }

  @Test
  @DisplayName("print_sample reports the I/O error code in hex after a panic when one is set")
  void shouldPrintIoErrorWhenPanicWithIoErrors() {
    com.robsartin.jsgb.graph.Gb.panicCode = 20;
    com.robsartin.jsgb.io.GbIo.ioErrors = 0x4;
    String out = Oracle.capture(ps -> TestSample.printSample(null, 0, ps));
    com.robsartin.jsgb.io.GbIo.ioErrors = 0;
    assertThat(out)
        .isEqualTo("\nOoops, we just ran into panic code 20!\n(The I/O error code is 0x4)\n");
  }

  @Test
  @DisplayName("the sample.correct header and stanza extraction work")
  void shouldExtractStanzasWhenReadingSampleCorrect() {
    assertThat(SampleCorrect.HEADER).isEqualTo("GraphBase samples generated by test_sample:\n");
    assertThat(SampleCorrect.stanza(0)).startsWith("\n\"raman(31,3,3,4)\"\n12 vertices, 96 arcs");
    assertThat(SampleCorrect.stanza(13)).isEqualTo("\nOoops, we just ran into panic code 30!\n");
    assertThat(SampleCorrect.stanza(15)).endsWith("->\"faded\"[430], 1[0]\n");
  }

  @Test
  @DisplayName("stanza 0: raman(31,3,0,4) at vertex 4")
  void shouldMatchSampleCorrectWhenRamanStanzaPrinted() {
    assertThat(Oracle.capture(ps -> TestSample.printSample(Raman.raman(31L, 3L, 0L, 4L), 4, ps)))
        .isEqualTo(SampleCorrect.stanza(0));
  }

  @Test
  @DisplayName("oracle_inc2.out cases are addressable by name")
  void shouldExtractCasesWhenReadingOracleFile() {
    assertThat(Oracle.inc2("board_dir"))
        .startsWith("\n\"board(3,3,0,0,-2,0,1)\"\n9 vertices, 10 arcs");
    assertThat(Oracle.inc2("random_lengths"))
        .startsWith("\n\"random_lengths(board(3,0,0,0,1,0,0),0,-3,3,0,9)\"");
    assertThat(Oracle.inc2Return("random_lengths")).isZero();
    assertThat(Oracle.inc2Return("random_lengths_null")).isEqualTo(50L);
    assertThat(Oracle.inc2("random_lengths_null")).isEmpty();
  }

  @Test
  @DisplayName("stanza 11: random_bigraph(300,3,1000,-1,0,dist,-500,500,666) at vertex 3")
  void shouldMatchSampleCorrectWhenRandomBigraphStanzaPrinted() {
    long[] dst = {0x20000000L, 0x10000000L, 0x10000000L};
    assertThat(
            Oracle.capture(
                ps ->
                    TestSample.printSample(
                        Rand.randomBigraph(300L, 3L, 1000L, -1L, null, dst, -500L, 500L, 666L),
                        3,
                        ps)))
        .isEqualTo(SampleCorrect.stanza(11));
  }

  @Test
  @DisplayName("stanza 1: board(1,1,2,-33,1,-2^31,1) at vertex 2000")
  void shouldMatchSampleCorrectWhenBoardStanzaPrinted() {
    assertThat(
            Oracle.capture(
                ps ->
                    TestSample.printSample(
                        Basic.board(1L, 1L, 2L, -33L, 1L, -0x40000000L - 0x40000000L, 1L),
                        2000,
                        ps)))
        .isEqualTo(SampleCorrect.stanza(1));
  }

  @Test
  @DisplayName("stanza 2: subsets(32,18,16,0,999,-999,0x80000000,1) at vertex 1")
  void shouldMatchSampleCorrectWhenSubsetsStanzaPrinted() {
    assertThat(
            Oracle.capture(
                ps ->
                    TestSample.printSample(
                        Basic.subsets(32L, 18L, 16L, 0L, 999L, -999L, 0x80000000L, 1L), 1, ps)))
        .isEqualTo(SampleCorrect.stanza(2));
  }

  @Test
  @DisplayName("test.gb written by the test_sample sequence is byte-identical to test.correct")
  void shouldWriteTestCorrectWhenSampleSequenceSaves() throws Exception {
    Graph g = Rand.randomGraph(3L, 10L, 1L, 1L, 0L, null, DST, 1L, 2L, 1L);
    Graph gg = Basic.complement(g, 1L, 1L, 0L);
    Vertex v = Gb.allocVertices(gg, 1)[0];
    v.name = Gb.saveString("Testing");
    gg.utilTypes = gg.utilTypes.substring(0, 10) + 'V' + gg.utilTypes.substring(11);
    gg.ww.V(v);
    Path out = dir.resolve("test.gb");
    assertThat(Save.saveGraph(gg, out.toString())).isZero();
    Gb.recycle(g);
    Gb.recycle(gg);
    String expected =
        new String(
            getClass().getResourceAsStream("/oracle/test.correct").readAllBytes(),
            StandardCharsets.ISO_8859_1);
    assertThat(Files.readString(out, StandardCharsets.ISO_8859_1)).isEqualTo(expected);
  }

  @Test
  @DisplayName(
      "stanza 3: gunion(random_lengths(restore_graph(test.gb)...), random_graph(...)) at vertex 2")
  void shouldMatchSampleCorrectWhenRestoredGraphStanzaPrinted() throws Exception {
    Path out = dir.resolve("test.gb");
    Files.write(out, getClass().getResourceAsStream("/oracle/test.correct").readAllBytes());
    Graph g = Save.restoreGraph(out.toString());
    assertThat(g).isNotNull();
    assertThat(Rand.randomLengths(g, 0L, 10L, 12L, DST, 2L)).isZero();
    Graph gg = Rand.randomGraph(3L, 10L, 1L, 1L, 0L, null, DST, 1L, 2L, 1L);
    assertThat(Oracle.capture(ps -> TestSample.printSample(Basic.gunion(g, gg, 1L, 0L), 2, ps)))
        .isEqualTo(SampleCorrect.stanza(3));
  }

  @Test
  @DisplayName(
      "the main sequence so far reproduces the header and stanzas 0 to 3 of sample.correct")
  void shouldMatchSampleCorrectPrefixWhenMainRuns() {
    String expected =
        SampleCorrect.HEADER
            + SampleCorrect.stanza(0)
            + SampleCorrect.stanza(1)
            + SampleCorrect.stanza(2)
            + SampleCorrect.stanza(3);
    assertThat(Oracle.capture(ps -> TestSample.run(ps, dir))).isEqualTo(expected);
    assertThat(dir.resolve("test.gb")).exists();
  }

  @Test
  @DisplayName("print_sample prints ONE for a boolean arc tip and a boolean V slot")
  void shouldPrintOneWhenTipOrSlotIsBoolean() {
    Graph g = Gb.newGraph(1L);
    g.id = "one";
    g.utilTypes = "VZZZZZZZZZZZZZ";
    g.vertices[0].name = "a";
    g.vertices[0].u.V(Gb.ONE);
    Gb.newArc(g.vertices[0], Gb.ONE, 2L);
    assertThat(Oracle.capture(ps -> TestSample.printSample(g, 0, ps)))
        .isEqualTo(
            "\n\"one\"\n1 vertices, 1 arcs, util_types VZZZZZZZZZZZZZ\nV0: \"a\"[ONE]\n   ->ONE, 2\n");
  }

  @Test
  @DisplayName("oracle_inc3a.out cases are addressable by name")
  void shouldExtractInc3aCasesWhenReadingOracleFile() {
    assertThat(Oracle.inc3a("words_top"))
        .startsWith("\n\"words(50,0,1000,1)\"\n50 vertices, 26 arcs");
    assertThat(Oracle.inc3aReturn("miles_distance")).isEqualTo(520L);
    assertThat(Oracle.inc3a("find_word")).isEqualTo("words\n|NULL\n|graph\n");
    assertThat(Oracle.inc3a("dijkstra_unreachable"))
        .isEqualTo("return=-1\nSorry, 0 is unreachable.\n");
  }
}
