package com.robsartin.jsgb.demo;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class TestSampleTest {

  @Test
  @DisplayName("print_sample reports a panic exactly as the C does")
  void shouldPrintPanicWhenGraphIsNull() {
    com.robsartin.jsgb.graph.Gb.panicCode = 30;
    com.robsartin.jsgb.io.GbIo.ioErrors = 0;
    String out = Oracle.capture(ps -> TestSample.printSample(null, 0, ps));
    assertThat(out).isEqualTo("\nOoops, we just ran into panic code 30!\n");
  }

  @Test
  @DisplayName("print_sample prints a small hand-built graph with util types")
  void shouldPrintGraphWhenVertexHasArcsAndSlots() {
    com.robsartin.jsgb.graph.Graph g = com.robsartin.jsgb.graph.Gb.newGraph(2L);
    g.id = "hand";
    g.utilTypes = "IZZZZZZAZZZZZZ";
    g.vertices[0].name = "a";
    g.vertices[1].name = "b";
    g.vertices[0].u.I = 7;
    com.robsartin.jsgb.graph.Gb.newEdge(g.vertices[0], g.vertices[1], 3L);
    g.vertices[0].arcs.b.A(g.vertices[1].arcs);
    String out = Oracle.capture(ps -> TestSample.printSample(g, 0, ps));
    assertThat(out)
        .isEqualTo(
            "\n\"hand\"\n2 vertices, 2 arcs, util_types IZZZZZZAZZZZZZ\nV0: \"a\"[7]\n   ->\"b\"[0], 3[->\"a\"[7]]\n");
  }

  @Test
  @DisplayName("the sample.correct header and stanza extraction work")
  void shouldExtractStanzasWhenReadingSampleCorrect() {
    assertThat(SampleCorrect.HEADER).isEqualTo("GraphBase samples generated by test_sample:\n");
    assertThat(SampleCorrect.stanza(0)).startsWith("\n\"raman(31,3,3,4)\"\n12 vertices, 96 arcs");
    assertThat(SampleCorrect.stanza(13)).isEqualTo("\nOoops, we just ran into panic code 30!\n");
    assertThat(SampleCorrect.stanza(15)).endsWith("->\"faded\"[430], 1[0]\n");
  }

  @Test
  @DisplayName("oracle_inc2.out cases are addressable by name")
  void shouldExtractCasesWhenReadingOracleFile() {
    assertThat(Oracle.inc2("board_dir"))
        .startsWith("\n\"board(3,3,0,0,-2,0,1)\"\n9 vertices, 10 arcs");
    assertThat(Oracle.inc2("random_lengths"))
        .startsWith("\n\"random_lengths(board(3,0,0,0,1,0,0),0,-3,3,0,9)\"");
    assertThat(Oracle.inc2Return("random_lengths")).isZero();
    assertThat(Oracle.inc2Return("random_lengths_null")).isEqualTo(50L);
    assertThat(Oracle.inc2("random_lengths_null")).isEmpty();
  }
}
